### ISSUE TITLE
Unable to copy the address in gui

### ISSUE THREAD

**Issue by samvicky26** [monerov/monerov-gui#2]
Unable to copy the address in gui

**Comment by jsonnentag** [comment]
I couldn't find it either for a long time and wasted a bunch of time copying it off, but if the monitor is turned up bright enough (I keep things dark) you can see the universal (I guess it is anyway) overlapping pages of the copy to clipboard symbol.

That "copy to clipboard" symbol really should be bigger and higher contrast though.  Or just put some text that says "Copy to Clipboard" and be done with it. . . .

It also wouldn't hurt to just allow the visible text to be highlighted and copied, which is what most people are likely to try and find doesn't work!

**Comment by miltonf** [comment]
Fixed at https://github.com/monerov/monerov-gui/commit/5d6dda09049066188ea5a227d366a6513be2cbc9. It's there on the bottom right corner but the coloring was off.
