### ISSUE TITLE
Mac os yosemite

### ISSUE THREAD

**Issue by micalways** [monerov/monerov-gui#3]
Hello MoneroV team
Mac os yosemite giu wallet release possible?
Thx!

**Comment by vanfactory** [comment]
GUI was compiled under Sierra. We would need to add a Yosemite server to the buildbot and that might take time, better upgrade for now.

**Comment by micalways** [comment]
I understand, however as many other people around...my older mac cannot upgrade anymore...

**Comment by miltonf** [comment]
We'll update when osx 10 is added. closing for now.
