### ISSUE TITLE
Importing xmr-snapshot; monerov-blockchain-import.exe problem 

### ISSUE THREAD

**Issue by Staz1st** [monerov/monerov-gui#5]
To claim my xmv from xmr I'm trying to start a new xmv-wallet.
I tried to import a _xmr-export.raw_ file I recently made. All this is happening on an external drive (D:\...).
I copied the "export"map in which the .raw file is, into 

> D:\AppData-Y\MoneroV

, being the map where the blockchain should be.
The wallet is going to be in: 

> D:\++XMV\

The wallet-software is extracted in: 

> D:\++XMV\monerov-wallet-gui-win64-0.13\build\release\bin

To run the import of the blockchain I made 2 bat-files to run but they crash cli on startup.
Any ideas what i'm doing wrong?
[import-v1.txt](https://github.com/monerov/monerov-gui/files/1996700/import-v1.txt)
[import-v2.txt](https://github.com/monerov/monerov-gui/files/1996701/import-v2.txt)
[monerov-blockchain-import.log](https://github.com/monerov/monerov-gui/files/1996787/monerov-blockchain-import.log)

Couldn't find a good step-by-step guide to retrieve xmv from xmr. They'r all missing important details in theyre procedures.
I'm also looking for a list of all commands you can use in cli or .bat-files.

**Comment by miltonf** [comment]
You are confusing two different operations, import and pop-blocks. Simply import the raw file with `monerov-blockchain-import`:
`./monerov-blockchain-import --input-file /root/blockchain.raw`

**Comment by Staz1st** [comment]
Made a new .bat : 
[import-v1.txt](https://github.com/monerov/monerov-gui/files/1997035/import-v1.txt)
following your instructions, adjusted dir of .raw file, being: _--input-file D:\AppData-Y\MoneroV\export_
but it keeps crashing

**Comment by miltonf** [comment]
Your command is incorrect. It should point to the blockhain.raw file after `--input-file`.

**Comment by Staz1st** [comment]
Ok. Thanks for your assistance.

**Comment by miltonf** [comment]
Resolved.
